### ISSUE TITLE
When an order fails. Should it be possible to resend it? 

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-betaling-frontend#100]
When an order is rejected in some way, as an example when address is missing. Should you be able to try to resend the order? 

This makes sense if a student is missing address and the address gets updated. If it should not be possible, it should be possible to delete a rejected order the same way you delete an order that isnt sent? Otherwise the history will slowly get filled with failed orders that you are unable to remove. An option is to add filter and by default only show the latest 30 days of orders in the order history. 

@asgeirn thoughts? :)

**Comment by asgeirn** [comment]
There should probably be options for both scenarios, both resending and deleting.

We are also missing more back-office features to be used by administrators (us) to manage data.  This back-office interface should have full editing capability on all available claims.

**Comment by OlaStalberg** [comment]
I think some backoffice user for each county would be appropriate seeing as they already have that control but in another system. If they can delete/remove/cancel invoices in their usual invoice system they should maybe have the rights to do so in ours.

**Comment by jennifer-fintlabs** [comment]
This function has been added to the new order history.
