### ISSUE TITLE
Import / upload customer list

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-betaling-frontend#91]
Add option to upload / import customer list for mass order creation

**Comment by OlaStalberg** [comment]
Is the thought here to use csv file? Could you elaborate? @asgeirn

**Comment by asgeirn** [comment]
> Is the thought here to use csv file? Could you elaborate? @asgeirn

Whatever the customer finds easiest.  I'd suggest that we support a list of customer names, pretty much the way Outlook supports pasting recipients to the `To` field that are resolved from the catalog.

**Comment by OlaStalberg** [comment]
Closed in #98
